"""add execution lease and heartbeat

Revision ID: 678e109b0185
Revises: 988615a91ef9
Create Date: 2026-07-31 22:23:52.472454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '678e109b0185'
down_revision: Union[str, Sequence[str], None] = '988615a91ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_executions', sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task_executions', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task_executions', sa.Column('attempt_count', sa.Integer(), server_default='1', nullable=False))
    op.create_index('ix_task_executions_lease_expires_at', 'task_executions', ['lease_expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_executions_lease_expires_at', table_name='task_executions')
    op.drop_column('task_executions', 'attempt_count')
    op.drop_column('task_executions', 'lease_expires_at')
    op.drop_column('task_executions', 'heartbeat_at')
    # ### end Alembic commands ###
