"""add asset checksum

Revision ID: 95056e376c5b
Revises: 8194edd05d08
Create Date: 2026-07-30 17:44:33.890183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95056e376c5b'
down_revision: Union[str, Sequence[str], None] = '8194edd05d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.add_column('assets', sa.Column('asset_checksum', sa.String(length=64), nullable=True))
    op.create_index('ix_asset_checksum', 'assets', ['asset_checksum'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.drop_index('ix_asset_checksum', table_name='assets')
    op.drop_column('assets', 'asset_checksum')
    # ### end Alembic commands ###