"""add task execution tracking fields

Revision ID: 988615a91ef9
Revises: 6c40478ae5e1
Create Date: 2026-07-30 20:05:30.225300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '988615a91ef9'
down_revision: Union[str, Sequence[str], None] = '6c40478ae5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_executions', sa.Column('project_id', sa.Integer(), nullable=False))
    op.add_column('task_executions', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.add_column('task_executions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_task_executions_asset_id', 'task_executions', ['asset_id'], unique=False)
    op.create_index('ix_task_executions_project_id', 'task_executions', ['project_id'], unique=False)
    op.create_index('ix_task_executions_status', 'task_executions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_executions_status', table_name='task_executions')
    op.drop_index('ix_task_executions_project_id', table_name='task_executions')
    op.drop_index('ix_task_executions_asset_id', table_name='task_executions')
    op.drop_column('task_executions', 'updated_at')
    op.drop_column('task_executions', 'asset_id')
    op.drop_column('task_executions', 'project_id')
    # ### end Alembic commands ###
