"""Inital commit-add-back_populates_in_asset

Revision ID: f1458315c1da
Revises: 72ac41afdff3
Create Date: 2026-07-21 17:18:47.874053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1458315c1da'
down_revision: Union[str, Sequence[str], None] = '72ac41afdff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
